[package]
authors = ["Kisio Digital <team.coretools@kisio.com>", "Guillaume Pinot <texitoi@texitoi.eu>"]
name = "transit_model"
version = "0.20.3"
license = "AGPL-3.0-only"
description = "Transit data management"
repository = "https://github.com/CanalTP/transit_model"
keywords = ["ntfs", "gtfs", "netex", "navitia", "transit"]
categories = ["data-structures", "encoding", "parser-implementations"]
edition = "2018"
readme = "README.md"
exclude = [
	".gitignore",
	".mergify.yml",
	".travis.yml",
	"CONTRIBUTING.md",
	"README.md",
	"examples/",
	"model-builder/",
	"src/documentation/",
	"tests/",
]

[package.metadata.cargo-udeps.ignore]
normal = ["minidom_writer", "md5"]

[badges]
travis-ci = { repository = "CanalTP/transit_model" }

[workspace]
members = [
	"gtfs2netexfr",
	"gtfs2ntfs",
	"ntfs2gtfs",
	"ntfs2netexfr",
	"ntfs2ntfs",
	"restrict-validity-period",
]

[features]
xmllint = ["proj"]

[dependencies]
chrono = "0.4"
csv = "1.1"
derivative = "2.1"
failure = "0.1"
geo = "0.13"
geo-types = "0.5"
iso4217 = "0.3"
lazy_static = "1.4"
log = "0.4"
md5 = "0.7"
minidom = "0.12"
minidom_ext = "1"
minidom_writer = "1"
num-traits = "0.2"
pretty_assertions = "0.6"
proj = { version = "0.17", optional = true }
quick-xml = "0.18"
relational_types = "1"
rust_decimal = "1.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
skip_error = { version = "1", features = ["log"] }
tempfile = "3"
typed_index_collection = "1"
walkdir = "2.3"
wkt = "0.7"
zip = "0.5"

[[test]]
name = "write_netex_france"
path = "tests/write_netex_france.rs"
required-features = ["proj"]

[dev-dependencies]
approx = "0.3"
rust_decimal_macros = "1.6"
